### ISSUE TITLE
CSGOV Profile is downloaded to wrong folder

### ISSUE THREAD

**Issue by jakubhnilicka** [Drupalcz/csgov-project#1]
Installation profile from csgov repo which have dependency in composer.json is downloaded to wrong place.
Instead to docroot/profile/contrib/csgov is downloaded into vendor/drupalcz/csgov and as a site installation not as a profile.

**Comment by jakubhnilicka** [comment]
I think that we don't need full drupal-scaffold in csgov profile composer.json.

**Comment by petrillek** [comment]
I think this has been fixed. Closing.
